using System.Reflection;

namespace Microsoft.PreviewFramework.App;

public class AppUIComponents : UIComponents<AppUIComponent, AppPreview>
{
    public void AddFromAssembly(Assembly assembly)
    {
        IEnumerable<UIComponentCategoryAttribute> uiComponentCategoryAttributes = assembly.GetCustomAttributes<UIComponentCategoryAttribute>();
        foreach (UIComponentCategoryAttribute uiComponentCategoryAttribute in uiComponentCategoryAttributes)
        {
            UIComponentCategory category = this.GetOrAddCategory(uiComponentCategoryAttribute.Name);

            foreach (Type type in uiComponentCategoryAttribute.UIComponentTypes)
            {
                AppUIComponent component = this.GetOrAddComponent(type);
                component.InitCategory(category);
            }
        }

        Type[] types = assembly.GetExportedTypes();
        foreach (Type type in types)
        {
            PreviewAttribute? typePreviewAttribute = type.GetCustomAttribute<PreviewAttribute>(false);
            if (typePreviewAttribute != null)
            {
                this.AddPreview(new ClassPreview(typePreviewAttribute, type));
            }

            MethodInfo[] methods = type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.DeclaredOnly);
            foreach (MethodInfo method in methods)
            {
                PreviewAttribute? previewAttribute = method.GetCustomAttribute<PreviewAttribute>(false);

                if (previewAttribute != null)
                {
                    this.AddPreview(new StaticMethodUIPreview(previewAttribute, method));
                }
            }

            if (CanBeAutoGeneratedPreview(type))
            {
                AppUIComponent? uiComponent = this.GetUIComponent(type.FullName);

                // If the type doesn't have any previews and this class can be an auto-generated preview, then add that
                if ((uiComponent == null || uiComponent.Previews.Count == 0) && CanBeAutoGeneratedPreview(type))
                {
                    uiComponent ??= this.GetOrAddComponent(type);

                    var preview = new ClassPreview(type, isAutoGenerated: true);
                    this.AddPreview(preview);
                }
            }
        }
    }

    private static bool CanBeAutoGeneratedPreview(Type type)
    {
        if (type.IsAbstract)
        {
            return false;
        }
  
        bool derivesFromContentPage = false;
        Type baseType = type.BaseType;
        while (baseType != null)
        {
            if (baseType.FullName == "Xamarin.Forms.ContentPage" || baseType.FullName == "Microsoft.Maui.Controls.ContentPage")
            {
                derivesFromContentPage = true;
                break;
            }
            baseType = baseType.BaseType;
        }

        if (! derivesFromContentPage)
        {
            return false;
        }

        // Check for a public or internal default constructor
        ConstructorInfo constructor = type.GetConstructor(Type.EmptyTypes);
        if (constructor == null || !(constructor.IsPublic || constructor.IsAssembly))
        {
            return false;
        }

        return true;
    }

    public AppUIComponent GetOrAddComponent(Type type)
    {
        string name = type.FullName;

        AppUIComponent? component = this.GetUIComponent(name);
        if (component == null)
        {
            component = new AppUIComponent(type, null);
            this.AddUIComponent(component);
        }

        return component;
    }

    public void AddPreview(AppPreview preview)
    {
        AppUIComponent component = this.GetOrAddComponent(preview.UIComponentType);
        component.AddPreview(preview);
    }
}
