namespace Microsoft.PreviewFramework.App;

public class ClassPreview : AppPreview
{
    bool isAutoGenerated = false;

    public ClassPreview(PreviewAttribute previewAttribute, Type type) : base(previewAttribute)
    {
        this.Type = type;
    }

    public ClassPreview(Type type, bool isAutoGenerated) : base(type)
    {
        this.Type = type;
        this.isAutoGenerated = isAutoGenerated;
    }

    public Type Type { get; }

    public override object Create()
    {
        return Activator.CreateInstance(this.Type);
    }

    public override Type? DefaultUIComponentType => null;

    public override string Name => this.Type.FullName;

    public override bool IsAutoGenerated => this.isAutoGenerated;
}
