namespace Microsoft.PreviewFramework.Tooling;

public class ClassPreview : ToolingPreview
{
    bool isAutoGenerated = false;

    public ClassPreview(string classFullName, string? displayName) : base(classFullName, displayName)
    {
    }

    public ClassPreview(string classFullName, bool isAutoGenerated) : base(classFullName, null)
    {
        this.isAutoGenerated = isAutoGenerated;
    }

    public override bool IsAutoGenerated => this.isAutoGenerated;
}
